name: JavaScript Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Run JavaScript Deployment Script
      run: |
        npm install # 如果你的脚本依赖了npm包
        node ./deploy.js
